### ISSUE TITLE
[Feature Request] Add documentation on how to create a geofence .json file

### ISSUE THREAD

**Issue by Coehill** [Stefal/Photo_filter#1]
A helpful feature of the photo_filter tool is the ability to move images around a specific location with the -j flag.  It would be appreciated if there was some sort of documentation on how to create a geojson file with one or more locations was provided.

**Comment by Stefal** [comment]
You're right.

and ... done : https://github.com/Stefal/Photo_filter/commit/4712c67388326a8adef699681779a4fd0a371672

**Comment by Coehill** [comment]
Thank you!
